### ISSUE TITLE
astroquery.alma fail

### ISSUE THREAD

**Issue by ridlo** [bosscha/alma-calibrator#1]
`astroquery.alma` fail when I run the ALMAQueryCal.py
I change my astroquery to the older version 0.3.1 but still got the same error.

http://nbviewer.jupyter.org/github/ridlo/radio_notebooks/blob/master/test_01_query.ipynb

Related issue: https://github.com/astropy/astroquery/issues/724 
Is there any changes in ALMA archive form (website)?

**Comment by bosscha** [comment]
I am not sure if it is a problem with astropy or the ALMA archive...

**Comment by bosscha** [comment]
It seems that it is an astrophysics issue. Need to issue a ticket for them. Their examples do not work neither ...

**Comment by ridlo** [comment]
I will close this issue
